# 05 - Model Interpretation

This notebook examines the trained models to identify the key features that drive income prediction. Using model-specific interpretation methods (e.g., coefficients, feature importance, SHAP values), it analyzes how different variables contribute to the models' predictions and extracts the most influential predictors of income.

## Imports

In [1]:
import sys

import numpy as np
import pandas as pd
import sklearn.metrics

from IPython.display import display, HTML

sys.path.append("../src")

from my_datasets import census
from my_datasets import dataframe_utils
import ml_utils
from ml_utils import feature_importance
from ml_utils import evaluation
from ml_utils import model_pipelines

## Helper Functions

### `train_full_model`

Reusable utility function that loads a previously trained model from disk if available. If no saved model exists, it trains a new model using the full dataset, saves it for future reuse, and then returns the fitted model.

In [2]:
def train_full_model(
    model_name,
    df,
    categorical_columns,
    numeric_columns,
    target_column,
    weight_column,
    model_filename_prefix="key_drivers"
):
    model_filename = f"{model_filename_prefix}-{model_name}.joblib"
    try:
        pipeline = census.load_model(model_filename)
        print(f"Loaded pretrained {model_name} model.")
    except FileNotFoundError:
        print(f"No pretrained {model_name} model found.")
        model = model_pipelines.get_prediction_models(
        	categorical_columns=categorical_columns,
        	numeric_columns=numeric_columns,
            remove_niu=True,
            select=model_name
        )
        
        import time
        from datetime import timedelta
        
        start = time.perf_counter()
        pipeline = evaluation.fit_model(
        	estimator=model,
        	X=data_df[categorical_columns + numeric_columns],
        	y=data_df[target_column],
        	sample_weight=(
                data_df[weight_column] / data_df[weight_column].mean()
            )
        )
        end = time.perf_counter()
        
        elapsed = end - start
        print(f"  {timedelta(seconds=elapsed)}")
    
        census.save_model(pipeline, model_filename)

    return pipeline

## Feature Exclusion

Several features have previously been selected for exclusion from the models. This section defines those features.

In [3]:
exclude_features = [
    "hispanic origin",
    "detailed occupation recode",
    "detailed industry recode",

    "veterans benefits",
    "detailed household and family stat",

    "family members under 18",
    "region of previous residence",
    "state of previous residence",

    "migration code-change in msa",
    "migration code-change in reg",
    "migration code-move within reg",
    "migration prev res in sunbelt",

    "year"
]

## Data Loading and Inspection

The cleaned, processed dataset is loaded into a dataframe and basic inspection is performed to verify that it has been loaded correctly.

The target and sample weight columns are identified, along with the numeric-categorical features.

In [4]:
data_df = census.load_processed_dataframe("clean_data.csv", header=0, verbose=False)

dataframe_utils.print_dataframe_info(data_df)

target_column = census.get_target_feature()
weight_column = census.get_sample_weights_feature()

numeric_categorical_features = census.get_numeric_categorical_features()

# # subsample for code testing
# from sklearn.model_selection import train_test_split
# data_df, _ = train_test_split(
#     data_df,
#     train_size=1000,
#     stratify=data_df[target_column],
#     random_state=42,
# )
# data_df = data_df.reset_index(drop=True)
# dataframe_utils.print_dataframe_info(data_df)

DataFrame Memory Usage: 362.04 MB

,dtype,count,non_null,null_count,unique,top,freq,mean,std,min,25%,50%,75%,max
age,int64,199523,199523,0,NaN,NaN,NaN,34.494199,22.310895,0.0,15.0,33.0,50.0,90.0
class of worker,str,199523,199523,0,9,Not in universe,100245,NaN,NaN,NaN,NaN,NaN,NaN,NaN
detailed industry recode,int64,199523,199523,0,NaN,NaN,NaN,15.35232,18.067129,0.0,0.0,0.0,33.0,51.0
detailed occupation recode,int64,199523,199523,0,NaN,NaN,NaN,11.306556,14.454204,0.0,0.0,0.0,26.0,46.0
education,str,199523,199523,0,17,High school graduate,48407,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wage per hour,int64,199523,199523,0,NaN,NaN,NaN,55.426908,274.896454,0.0,0.0,0.0,0.0,9999.0
enroll in edu inst last wk,str,199523,199523,0,3,Not in universe,186943,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marital stat,str,199523,199523,0,7,Never married,86485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
major industry code,str,199523,199523,0,24,Not in universe or children,100684,NaN,NaN,NaN,NaN,NaN,NaN,NaN
major occupation code,str,199523,199523,0,15,Not in universe,100684,NaN,NaN,NaN,NaN,NaN,NaN,NaN
race,str,199523,199523,0,5,White,167365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hispanic origin,str,198649,198649,874,9,All other,171907,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sex,str,199523,199523,0,2,Female,103984,NaN,NaN,NaN,NaN,NaN,NaN,NaN
member of a labor union,str,199523,199523,0,3,Not in universe,180459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reason for unemployment,str,199523,199523,0,6,Not in universe,193453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
full or part time employment stat,str,199523,199523,0,8,Children or Armed Forces,123769,NaN,NaN,NaN,NaN,NaN,NaN,NaN
capital gains,int64,199523,199523,0,NaN,NaN,NaN,434.71899,4697.53128,0.0,0.0,0.0,0.0,99999.0
capital losses,int64,199523,199523,0,NaN,NaN,NaN,37.313788,271.896428,0.0,0.0,0.0,0.0,4608.0
dividends from stocks,int64,199523,199523,0,NaN,NaN,NaN,197.529533,1984.163658,0.0,0.0,0.0,0.0,99999.0
tax filer stat,str,199523,199523,0,6,Nonfiler,75094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region of previous residence,str,199523,199523,0,6,Not in universe,183750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state of previous residence,str,198815,198815,708,50,Not in universe,183750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
detailed household and family stat,str,199523,199523,0,38,Householder,53248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
detailed household summary in household,str,199523,199523,0,8,Householder,75475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weight,float64,199523,199523,0,NaN,NaN,NaN,1740.380269,993.768156,37.87,1061.615,1618.31,2188.61,18656.3
migration code-change in msa,str,99827,99827,99696,9,Nonmover,82538,NaN,NaN,NaN,NaN,NaN,NaN,NaN
migration code-change in reg,str,99827,99827,99696,8,Nonmover,82538,NaN,NaN,NaN,NaN,NaN,NaN,NaN
migration code-move within reg,str,99827,99827,99696,9,Nonmover,82538,NaN,NaN,NaN,NaN,NaN,NaN,NaN
live in this house 1 year ago,str,199523,199523,0,3,Not in universe under 1 year old,101212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
migration prev res in sunbelt,str,99827,99827,99696,3,Not in universe,84054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num persons worked for employer,int64,199523,199523,0,NaN,NaN,NaN,1.95618,2.365126,0.0,0.0,1.0,4.0,6.0
family members under 18,str,199523,199523,0,5,Not in universe,144232,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country of birth father,str,192810,192810,6713,42,United-States,159163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country of birth mother,str,193404,193404,6119,42,United-States,160479,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country of birth self,str,196130,196130,3393,42,United-States,176989,NaN,NaN,NaN,NaN,NaN,NaN,NaN
citizenship,str,199523,199523,0,5,Native- Born in the United States,176992,NaN,NaN,NaN,NaN,NaN,NaN,NaN
own business or self employed,int64,199523,199523,0,NaN,NaN,NaN,0.175438,0.553694,0.0,0.0,0.0,0.0,2.0
fill inc questionnaire for veteran's admin,str,199523,199523,0,3,Not in universe,197539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
veterans benefits,int64,199523,199523,0,NaN,NaN,NaN,1.514833,0.851473,0.0,2.0,2.0,2.0,2.0
weeks worked in year,int64,199523,199523,0,NaN,NaN,NaN,23.174897,24.411488,0.0,0.0,8.0,52.0,52.0
year,int64,199523,199523,0,NaN,NaN,NaN,94.499672,0.500001,94.0,94.0,94.0,95.0,95.0
label,str,199523,199523,0,2,- 50000.,187141,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,age,class of worker,detailed industry recode,detailed occupation recode,education,wage per hour,enroll in edu inst last wk,marital stat,major industry code,major occupation code,race,hispanic origin,sex,member of a labor union,reason for unemployment,full or part time employment stat,capital gains,capital losses,dividends from stocks,tax filer stat,region of previous residence,state of previous residence,detailed household and family stat,detailed household summary in household,weight,migration code-change in msa,migration code-change in reg,migration code-move within reg,live in this house 1 year ago,migration prev res in sunbelt,num persons worked for employer,family members under 18,country of birth father,country of birth mother,country of birth self,citizenship,own business or self employed,fill inc questionnaire for veteran's admin,veterans benefits,weeks worked in year,year,label
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Other Rel 18+ ever marr not in subfamily,Other relative of householder,1700.09,NaN,NaN,NaN,Not in universe under 1 year old,NaN,0,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Head of household,South,Arkansas,Householder,Householder,1053.55,MSA to MSA,Same county,Same county,No,Yes,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child 18+ never marr Not in a subfamily,Child 18 or older,991.95,NaN,NaN,NaN,Not in universe under 1 year old,NaN,0,Not in universe,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1758.14,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1069.16,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199518,87,Not in universe,0,0,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,White,All other,Male,Not in universe,Not in universe,Not in labor force,0,0,0,Joint both 65+,Not in universe,Not in universe,Householder,Householder,955.27,NaN,NaN,NaN,Not in universe under 1 year old,NaN,0,Not in universe,Canada,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
199519,65,Self-employed-incorporated,37,2,11th grade,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,6418,0,9,Joint one under 65 & one 65+,Not in universe,Not in universe,Householder,Householder,687.19,Nonmover,Nonmover,Nonmover,Yes,Not in universe,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
199520,47,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,157,Joint both under 65,Not in universe,Not in universe,Householder,Householder,1923.03,NaN,NaN,NaN,Not in universe under 1 year old,NaN,6,Not in universe,Poland,Poland,Germany,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,95,- 50000.
199521,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,4664.87,NaN,NaN,NaN,Not in universe under 1 year old,NaN,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
199522,32,Private,42,30,High school graduate,0,Not in universe,Never married,Medical except hospital,Other service,Black,All other,Female,No,Not in universe,Children or Armed Forces,0,0,0,Single,Not in universe,Not in universe,Nonfamily householder,Householder,1830.11,Nonmover,Nonmover,Nonmover,Yes,Not in universe,6,Not in universe,NaN,NaN,NaN,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,- 50000.

## Feature Type Separation and Adjustments

The dataset features are split into categorical and numeric column groups, with additional numeric-categorical features explicitly treated as categorical.

Adjustments are made to ensure correct feature assignment and prevent data leakage. The target column is removed from the categorical feature list, while the sample weight column is removed from the numeric feature list. In addition, all preselected excluded features are removed from consideration.

In [5]:
categorical_columns, numeric_columns = ml_utils.get_categorical_numeric_split(
    data_df,
    treat_as_categorical=numeric_categorical_features
)

exclude_set = set(exclude_features)
exclude_set.update([target_column, weight_column])

categorical_columns = [
    column
    for column in categorical_columns
    if column not in exclude_set
]

numeric_columns = [
    column
    for column in numeric_columns
    if column not in exclude_set
]

## Model Interpretation

In this section, the selected models are trained on the full processed dataset to identify the features most strongly associated with income. The resulting models and interpretation outputs are saved for subsequent analysis.

### LASSO Logistic Regression

In [6]:
pipeline = train_full_model(
    "lasso_logistic_regression",
    data_df,
    categorical_columns,
    numeric_columns,
    target_column,
    weight_column
)
display(pipeline)

importance_df = feature_importance.logistic_regression_importance(pipeline)
census.save_results_dataframe(
    importance_df, filename=f"key_drivers-lasso_logistic_regression.csv"
)

with pd.option_context(
	"display.max_colwidth", None,
	"display.max_columns", None,
	"display.width", None
):
    feature_importance.display_logistic_regression_importance(importance_df)

Loaded pretrained lasso_logistic_regression model.

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoderWithIgnore(handle_unknown='ignore',
                                                                          ignore_categories=['Not '
                                                                                             'in '
                                                                                             'universe',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'or '
                                                                                             'children',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'under '
                                                                                             '1 '
                                                                                             'year '
                                                                                             'old',
                                                                                             'Children '
                                                                                             'or '
                                                                                             'Armed '
                                                                                             'Forces',
                                                                                             nan],
                                                                          sparse_output=False),
                                                  ['class of worker',
                                                   'education',
                                                   'enroll in edu inst last wk'...
                                                   'employed',
                                                   'fill inc questionnaire for '
                                                   "veteran's admin"]),
                                                 ('numeric',
                                                  Pipeline(steps=[('SimpleImputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('StandardScaler',
                                                                   StandardScaler())]),
                                                  ['age', 'wage per hour',
                                                   'capital gains',
                                                   'capital losses',
                                                   'dividends from stocks',
                                                   'weeks worked in year'])])),
                ('LogisticRegression',
                 LogisticRegression(l1_ratio=1, random_state=42,
                                    solver='saga'))])

2026-06-24 15:39:28,901 - INFO - Saved DataFrame to results directory: /Users/jagraves21/census-income-ml-project/data/Census/results/key_drivers-lasso_logistic_regression.csv

,feature_raw,feature_type,feature_name,feature_value,coefficient,abs_coefficient,odds_ratio
0,categorical__education_Doctorate degree(PhD EdD),categorical,education,Doctorate degree(PhD EdD),2.113870,2.113870,8.280220
1,categorical__education_Prof school degree (MD DDS DVM LLB JD),categorical,education,Prof school degree (MD DDS DVM LLB JD),2.013194,2.013194,7.487191
2,categorical__tax filer stat_Nonfiler,categorical,tax filer stat,Nonfiler,-1.702619,1.702619,0.182206
3,categorical__sex_Female,categorical,sex,Female,-1.466858,1.466858,0.230649
4,categorical__education_Masters degree(MA MS MEng MEd MSW MBA),categorical,education,Masters degree(MA MS MEng MEd MSW MBA),1.295326,1.295326,3.652188
...,...,...,...,...,...,...,...
252,categorical__country of birth self_Panama,categorical,country of birth self,Panama,0.000000,0.000000,1.000000
253,categorical__country of birth self_Portugal,categorical,country of birth self,Portugal,0.000000,0.000000,1.000000
254,categorical__country of birth self_Thailand,categorical,country of birth self,Thailand,0.000000,0.000000,1.000000
255,categorical__country of birth self_Vietnam,categorical,country of birth self,Vietnam,0.000000,0.000000,1.000000
256,categorical__country of birth self_Yugoslavia,categorical,country of birth self,Yugoslavia,0.000000,0.000000,1.000000

,feature_raw,feature_type,feature_name,feature_value,coefficient,abs_coefficient,odds_ratio
0,categorical__education_Doctorate degree(PhD EdD),categorical,education,Doctorate degree(PhD EdD),2.113870,2.113870,8.280220
1,categorical__education_Prof school degree (MD DDS DVM LLB JD),categorical,education,Prof school degree (MD DDS DVM LLB JD),2.013194,2.013194,7.487191
4,categorical__education_Masters degree(MA MS MEng MEd MSW MBA),categorical,education,Masters degree(MA MS MEng MEd MSW MBA),1.295326,1.295326,3.652188
6,numeric__weeks worked in year,numeric,weeks worked in year,NaN,1.116011,1.116011,3.052653
11,categorical__major occupation code_Executive admin and managerial,categorical,major occupation code,Executive admin and managerial,0.946532,0.946532,2.576758

,feature_raw,feature_type,feature_name,feature_value,coefficient,abs_coefficient,odds_ratio
2,categorical__tax filer stat_Nonfiler,categorical,tax filer stat,Nonfiler,-1.702619,1.702619,0.182206
3,categorical__sex_Female,categorical,sex,Female,-1.466858,1.466858,0.230649
5,categorical__education_10th grade,categorical,education,10th grade,-1.139901,1.139901,0.319851
7,categorical__major industry code_Social services,categorical,major industry code,Social services,-1.055915,1.055915,0.347874
8,categorical__education_5th or 6th grade,categorical,education,5th or 6th grade,-1.045202,1.045202,0.351621

  feature_group  mean_abs_coefficient
0   categorical             61.456557
1       numeric              2.793752

,feature_type,feature_name,mean_abs_coefficient
0,numeric,weeks worked in year,1.116011
1,categorical,sex,0.898035
2,categorical,education,0.827111
3,numeric,age,0.713407
4,categorical,own business or self employed,0.576206
5,categorical,major occupation code,0.518401
6,categorical,tax filer stat,0.477588
7,numeric,capital gains,0.454175
8,numeric,dividends from stocks,0.349415
9,categorical,enroll in edu inst last wk,0.342183
10,categorical,detailed household summary in household,0.339653
11,categorical,citizenship,0.318865
12,categorical,race,0.318865
13,categorical,major industry code,0.303967
14,categorical,class of worker,0.299031
15,categorical,num persons worked for employer,0.295831
16,categorical,fill inc questionnaire for veteran's admin,0.242727
17,categorical,marital stat,0.212602
18,categorical,live in this house 1 year ago,0.169626
19,numeric,capital losses,0.152413
20,categorical,member of a labor union,0.134408
21,categorical,full or part time employment stat,0.119745
22,categorical,country of birth self,0.099613
23,categorical,country of birth mother,0.095230
24,categorical,country of birth father,0.089346
25,categorical,reason for unemployment,0.069483
26,numeric,wage per hour,0.008330

### Ridge Logistic Regression

In [7]:
pipeline = train_full_model(
    "ridge_logistic_regression",
    data_df,
    categorical_columns,
    numeric_columns,
    target_column,
    weight_column
)
display(pipeline)

importance_df = feature_importance.logistic_regression_importance(pipeline)
census.save_results_dataframe(
    importance_df, filename=f"key_drivers-ridge_logistic_regression.csv"
)

with pd.option_context(
	"display.max_colwidth", None,
	"display.max_columns", None,
	"display.width", None
):
    feature_importance.display_logistic_regression_importance(importance_df)

Loaded pretrained ridge_logistic_regression model.

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoderWithIgnore(handle_unknown='ignore',
                                                                          ignore_categories=['Not '
                                                                                             'in '
                                                                                             'universe',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'or '
                                                                                             'children',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'under '
                                                                                             '1 '
                                                                                             'year '
                                                                                             'old',
                                                                                             'Children '
                                                                                             'or '
                                                                                             'Armed '
                                                                                             'Forces',
                                                                                             nan],
                                                                          sparse_output=False),
                                                  ['class of worker',
                                                   'education',
                                                   'enroll in edu inst last wk'...
                                                   'own business or self '
                                                   'employed',
                                                   'fill inc questionnaire for '
                                                   "veteran's admin"]),
                                                 ('numeric',
                                                  Pipeline(steps=[('SimpleImputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('StandardScaler',
                                                                   StandardScaler())]),
                                                  ['age', 'wage per hour',
                                                   'capital gains',
                                                   'capital losses',
                                                   'dividends from stocks',
                                                   'weeks worked in year'])])),
                ('LogisticRegression',
                 LogisticRegression(l1_ratio=0, random_state=42))])

2026-06-24 15:39:29,023 - INFO - Saved DataFrame to results directory: /Users/jagraves21/census-income-ml-project/data/Census/results/key_drivers-ridge_logistic_regression.csv

,feature_raw,feature_type,feature_name,feature_value,coefficient,abs_coefficient,odds_ratio
0,categorical__education_Doctorate degree(PhD EdD),categorical,education,Doctorate degree(PhD EdD),2.177892,2.177892,8.827680
1,categorical__education_Prof school degree (MD DDS DVM LLB JD),categorical,education,Prof school degree (MD DDS DVM LLB JD),2.096429,2.096429,8.137060
2,categorical__tax filer stat_Nonfiler,categorical,tax filer stat,Nonfiler,-1.766543,1.766543,0.170923
3,categorical__sex_Female,categorical,sex,Female,-1.503386,1.503386,0.222376
4,categorical__education_5th or 6th grade,categorical,education,5th or 6th grade,-1.423451,1.423451,0.240881
...,...,...,...,...,...,...,...
252,categorical__country of birth self_Portugal,categorical,country of birth self,Portugal,0.012605,0.012605,1.012685
253,numeric__wage per hour,numeric,wage per hour,NaN,-0.008246,0.008246,0.991788
254,categorical__country of birth self_Hungary,categorical,country of birth self,Hungary,-0.006383,0.006383,0.993638
255,categorical__detailed household summary in household_Child under 18 ever married,categorical,detailed household summary in household,Child under 18 ever married,-0.003438,0.003438,0.996568
256,categorical__marital stat_Separated,categorical,marital stat,Separated,0.000888,0.000888,1.000888

,feature_raw,feature_type,feature_name,feature_value,coefficient,abs_coefficient,odds_ratio
0,categorical__education_Doctorate degree(PhD EdD),categorical,education,Doctorate degree(PhD EdD),2.177892,2.177892,8.827680
1,categorical__education_Prof school degree (MD DDS DVM LLB JD),categorical,education,Prof school degree (MD DDS DVM LLB JD),2.096429,2.096429,8.137060
5,categorical__education_Masters degree(MA MS MEng MEd MSW MBA),categorical,education,Masters degree(MA MS MEng MEd MSW MBA),1.362621,1.362621,3.906419
6,numeric__weeks worked in year,numeric,weeks worked in year,NaN,1.102071,1.102071,3.010395
10,categorical__country of birth self_Scotland,categorical,country of birth self,Scotland,1.016819,1.016819,2.764388

,feature_raw,feature_type,feature_name,feature_value,coefficient,abs_coefficient,odds_ratio
2,categorical__tax filer stat_Nonfiler,categorical,tax filer stat,Nonfiler,-1.766543,1.766543,0.170923
3,categorical__sex_Female,categorical,sex,Female,-1.503386,1.503386,0.222376
4,categorical__education_5th or 6th grade,categorical,education,5th or 6th grade,-1.423451,1.423451,0.240881
7,categorical__education_9th grade,categorical,education,9th grade,-1.072956,1.072956,0.341996
8,categorical__education_1st 2nd 3rd or 4th grade,categorical,education,1st 2nd 3rd or 4th grade,-1.053289,1.053289,0.348789

  feature_group  mean_abs_coefficient
0   categorical             83.035751
1       numeric              2.769060

,feature_type,feature_name,mean_abs_coefficient
0,numeric,weeks worked in year,1.102071
1,categorical,sex,0.931119
2,categorical,education,0.902364
3,numeric,age,0.708416
4,categorical,own business or self employed,0.620746
5,categorical,major occupation code,0.549173
6,categorical,tax filer stat,0.498243
7,categorical,enroll in edu inst last wk,0.477674
8,numeric,capital gains,0.449972
9,categorical,race,0.372448
10,categorical,citizenship,0.372448
11,categorical,detailed household summary in household,0.372423
12,categorical,class of worker,0.354915
13,numeric,dividends from stocks,0.348062
14,categorical,major industry code,0.337203
15,categorical,num persons worked for employer,0.322104
16,categorical,full or part time employment stat,0.307294
17,categorical,fill inc questionnaire for veteran's admin,0.300142
18,categorical,marital stat,0.266288
19,categorical,country of birth self,0.217181
20,categorical,country of birth mother,0.212421
21,categorical,country of birth father,0.209803
22,categorical,live in this house 1 year ago,0.178138
23,numeric,capital losses,0.152294
24,categorical,member of a labor union,0.139069
25,categorical,reason for unemployment,0.135907
26,numeric,wage per hour,0.008246

### Decision Tree

In [8]:
pipeline = train_full_model(
    "decision_tree",
    data_df,
    categorical_columns,
    numeric_columns,
    target_column,
    weight_column
)
display(pipeline)

importance_df = feature_importance.decision_tree_importance(pipeline)
census.save_results_dataframe(
    importance_df, filename=f"key_drivers-decision_tree.csv"
)

with pd.option_context(
	"display.max_colwidth", None,
	"display.max_columns", None,
	"display.width", None
):
    feature_importance.display_decision_tree_importance(importance_df)

Loaded pretrained decision_tree model.

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoderWithIgnore(handle_unknown='ignore',
                                                                          ignore_categories=['Not '
                                                                                             'in '
                                                                                             'universe',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'or '
                                                                                             'children',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'under '
                                                                                             '1 '
                                                                                             'year '
                                                                                             'old',
                                                                                             'Children '
                                                                                             'or '
                                                                                             'Armed '
                                                                                             'Forces',
                                                                                             nan],
                                                                          sparse_output=False),
                                                  ['class of worker',
                                                   'education',
                                                   'enroll in edu inst last wk'...
                                                   'own business or self '
                                                   'employed',
                                                   'fill inc questionnaire for '
                                                   "veteran's admin"]),
                                                 ('numeric',
                                                  Pipeline(steps=[('SimpleImputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('StandardScaler',
                                                                   StandardScaler())]),
                                                  ['age', 'wage per hour',
                                                   'capital gains',
                                                   'capital losses',
                                                   'dividends from stocks',
                                                   'weeks worked in year'])])),
                ('DecisionTreeClassifier',
                 DecisionTreeClassifier(random_state=42))])

2026-06-24 15:39:29,147 - INFO - Saved DataFrame to results directory: /Users/jagraves21/census-income-ml-project/data/Census/results/key_drivers-decision_tree.csv

,feature_raw,feature_type,feature_name,feature_value,gini_importance
0,numeric__age,numeric,age,NaN,0.126628
1,numeric__capital gains,numeric,capital gains,NaN,0.126373
2,numeric__dividends from stocks,numeric,dividends from stocks,NaN,0.099272
3,numeric__weeks worked in year,numeric,weeks worked in year,NaN,0.071253
4,categorical__sex_Male,categorical,sex,Male,0.031487
5,numeric__capital losses,numeric,capital losses,NaN,0.026177
6,categorical__major occupation code_Professional specialty,categorical,major occupation code,Professional specialty,0.022069
7,categorical__major occupation code_Executive admin and managerial,categorical,major occupation code,Executive admin and managerial,0.020292
8,numeric__wage per hour,numeric,wage per hour,NaN,0.013190
9,categorical__live in this house 1 year ago_Yes,categorical,live in this house 1 year ago,Yes,0.013050

  feature_group  mean_gini_importance
0   categorical              0.537107
1       numeric              0.462893

,feature_type,feature_name,mean_gini_importance
0,numeric,age,0.126628
1,numeric,capital gains,0.126373
2,numeric,dividends from stocks,0.099272
3,numeric,weeks worked in year,0.071253
4,numeric,capital losses,0.026177
5,categorical,sex,0.017294
6,numeric,wage per hour,0.013190
7,categorical,live in this house 1 year ago,0.009353
8,categorical,num persons worked for employer,0.006759
9,categorical,own business or self employed,0.006342
10,categorical,member of a labor union,0.005635
11,categorical,major occupation code,0.004837
12,categorical,education,0.004032
13,categorical,class of worker,0.003905
14,categorical,major industry code,0.003701
15,categorical,full or part time employment stat,0.003395
16,categorical,tax filer stat,0.003133
17,categorical,marital stat,0.002915
18,categorical,race,0.002859
19,categorical,detailed household summary in household,0.002551
20,categorical,citizenship,0.001434
21,categorical,fill inc questionnaire for veteran's admin,0.001273
22,categorical,reason for unemployment,0.000543
23,categorical,country of birth mother,0.000437
24,categorical,country of birth father,0.000379
25,categorical,country of birth self,0.000214
26,categorical,enroll in edu inst last wk,0.000113

### XGBoost

In [9]:
pipeline = train_full_model(
    "xgboost",
    data_df,
    categorical_columns,
    numeric_columns,
    target_column,
    weight_column
)
display(pipeline)

importance_df = feature_importance.xgboost_importance(
    pipeline, data_df[categorical_columns + numeric_columns]
)
census.save_results_dataframe(
    importance_df, filename=f"key_drivers-xgboost.csv"
)

with pd.option_context(
	"display.max_colwidth", None,
	"display.max_columns", None,
	"display.width", None
):
    feature_importance.display_xgboost_importance(importance_df)

Loaded pretrained xgboost model.

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoderWithIgnore(handle_unknown='ignore',
                                                                          ignore_categories=['Not '
                                                                                             'in '
                                                                                             'universe',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'or '
                                                                                             'children',
                                                                                             'Not '
                                                                                             'in '
                                                                                             'universe '
                                                                                             'under '
                                                                                             '1 '
                                                                                             'year '
                                                                                             'old',
                                                                                             'Children '
                                                                                             'or '
                                                                                             'Armed '
                                                                                             'Forces',
                                                                                             nan],
                                                                          sparse_output=False),
                                                  ['class of worker',
                                                   'education',
                                                   'enroll in edu inst last wk'...
                                                                   SimpleImputer(strategy='median')),
                                                                  ('StandardScaler',
                                                                   StandardScaler())]),
                                                  ['age', 'wage per hour',
                                                   'capital gains',
                                                   'capital losses',
                                                   'dividends from stocks',
                                                   'weeks worked in year'])])),
                ('XGBStringClassifier',
                 XGBStringClassifier(colsample_bytree=0.8,
                                     enable_categorical=False,
                                     eval_metric='logloss', learning_rate=0.05,
                                     max_depth=4, n_estimators=300, n_jobs=-1,
                                     random_state=42, subsample=0.8))])

2026-06-24 15:40:00,333 - INFO - Saved DataFrame to results directory: /Users/jagraves21/census-income-ml-project/data/Census/results/key_drivers-xgboost.csv

,feature_raw,feature_type,feature_name,feature_value,mean_abs_shap,mean_shap,positive_ratio
0,numeric__weeks worked in year,numeric,weeks worked in year,NaN,0.909304,-0.449554,0.394962
1,numeric__age,numeric,age,NaN,0.894676,-0.622140,0.473785
2,categorical__tax filer stat_Nonfiler,categorical,tax filer stat,Nonfiler,0.598825,-0.457938,0.623632
3,categorical__sex_Female,categorical,sex,Female,0.303162,-0.081856,0.478837
4,numeric__dividends from stocks,numeric,dividends from stocks,NaN,0.234979,-0.100083,0.103281
5,numeric__capital gains,numeric,capital gains,NaN,0.143841,-0.063823,0.020629
6,categorical__education_Bachelors degree(BA AB BS),categorical,education,Bachelors degree(BA AB BS),0.143535,-0.063166,0.099798
7,categorical__detailed household summary in household_Householder,categorical,detailed household summary in household,Householder,0.140654,-0.064475,0.378142
8,categorical__num persons worked for employer_6,categorical,num persons worked for employer,6,0.130913,-0.057791,0.183172
9,categorical__major occupation code_Executive admin and managerial,categorical,major occupation code,Executive admin and managerial,0.118272,-0.047846,0.062624

  feature_group  mean_mean_abs_shap
0   categorical            2.934445
1       numeric            2.280688

,feature_type,feature_name,mean_mean_abs_shap
0,numeric,weeks worked in year,0.909304
1,numeric,age,0.894676
2,numeric,dividends from stocks,0.234979
3,categorical,sex,0.173020
4,numeric,capital gains,0.143841
5,categorical,tax filer stat,0.106438
6,numeric,capital losses,0.061031
7,numeric,wage per hour,0.036856
8,categorical,num persons worked for employer,0.036039
9,categorical,major occupation code,0.032150
10,categorical,education,0.030722
11,categorical,detailed household summary in household,0.026700
12,categorical,marital stat,0.015916
13,categorical,class of worker,0.011119
14,categorical,own business or self employed,0.007169
15,categorical,major industry code,0.007138
16,categorical,race,0.006246
17,categorical,live in this house 1 year ago,0.005344
18,categorical,fill inc questionnaire for veteran's admin,0.004829
19,categorical,full or part time employment stat,0.004484
20,categorical,member of a labor union,0.001786
21,categorical,citizenship,0.001255
22,categorical,enroll in edu inst last wk,0.000722
23,categorical,country of birth self,0.000431
24,categorical,country of birth father,0.000248
25,categorical,reason for unemployment,0.000073
26,categorical,country of birth mother,0.000056